name: pcenv
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - blas=1.0=mkl
  - brotli-python=1.0.9=py39hd77b12b_8
  - ca-certificates=2024.7.2=haa95532_0
  - certifi=2024.7.4=py39haa95532_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cccl=12.6.37=0
  - cuda-cccl_win-64=12.6.37=0
  - cuda-cudart=12.4.127=0
  - cuda-cudart-dev=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.0=0
  - cuda-libraries-dev=12.4.0=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvrtc-dev=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.6.37=0
  - cuda-opencl-dev=12.6.37=0
  - cuda-profiler-api=12.6.37=0
  - cuda-runtime=12.4.0=0
  - cuda-version=12.6=3
  - filelock=3.13.1=py39haa95532_0
  - freetype=2.12.1=ha860e81_0
  - gmpy2=2.1.2=py39h7f96b67_0
  - idna=3.7=py39haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.4=py39haa95532_0
  - jpeg=9e=h827c3e9_3
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libcublas=12.4.2.65=0
  - libcublas-dev=12.4.2.65=0
  - libcufft=11.2.0.44=0
  - libcufft-dev=11.2.0.44=0
  - libcurand=10.3.7.37=0
  - libcurand-dev=10.3.7.37=0
  - libcusolver=11.6.0.99=0
  - libcusolver-dev=11.6.0.99=0
  - libcusparse=12.3.0.142=0
  - libcusparse-dev=12.3.0.142=0
  - libdeflate=1.17=h2bbff1b_1
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libnpp=12.2.5.2=0
  - libnpp-dev=12.2.5.2=0
  - libnvfatbin=12.6.20=0
  - libnvfatbin-dev=12.6.20=0
  - libnvjitlink=12.4.99=0
  - libnvjitlink-dev=12.4.99=0
  - libnvjpeg=12.3.1.89=0
  - libnvjpeg-dev=12.3.1.89=0
  - libpng=1.6.39=h8cc25b3_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=2.1.3=py39h2bbff1b_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py39h2bbff1b_1
  - mkl_fft=1.3.8=py39h2bbff1b_0
  - mkl_random=1.2.4=py39h59b6b97_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.3.0=py39haa95532_0
  - networkx=3.2.1=py39haa95532_0
  - numpy=1.26.4=py39h055cbcc_0
  - numpy-base=1.26.4=py39h65a83cf_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.14=h827c3e9_0
  - pillow=10.4.0=py39h827c3e9_0
  - pip=24.2=py39haa95532_0
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.19=h1aa4202_1
  - pytorch=2.4.0=py3.9_cuda12.4_cudnn9_0
  - pytorch-cuda=12.4=h3fd98bf_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py39h2bbff1b_0
  - requests=2.32.3=py39haa95532_0
  - setuptools=72.1.0=py39haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - sympy=1.12=py39haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - typing_extensions=4.11.0=py39haa95532_0
  - tzdata=2024a=h04d1e81_0
  - urllib3=2.2.2=py39haa95532_0
  - vc=14.40=h2eaa2aa_0
  - vs2015_runtime=14.40.33807=h98bb1dd_0
  - wheel=0.43.0=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.5=hd43e919_2
  - pip:
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - attrs==24.2.0
      - click==8.1.7
      - colorama==0.4.6
      - docker-pycreds==0.4.0
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - joblib==1.4.2
      - multidict==6.0.5
      - platformdirs==4.2.2
      - protobuf==5.27.3
      - psutil==6.0.0
      - pyg-lib==0.4.0+pt24cu124
      - pyparsing==3.1.2
      - scikit-learn==1.5.1
      - scipy==1.13.1
      - sentry-sdk==2.13.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - threadpoolctl==3.5.0
      - torch-cluster==1.6.3+pt24cu124
      - torch-geometric==2.5.3
      - torch-scatter==2.1.2+pt24cu124
      - torch-sparse==0.6.18+pt24cu124
      - torch-spline-conv==1.2.2+pt24cu124
      - torchaudio==2.4.0
      - torchvision==0.19.0
      - tqdm==4.66.5
      - wandb==0.17.7
      - yarl==1.9.4
prefix: C:\Users\hiren\anaconda3\envs\pcenv
